# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         WWW-Sucksub-Extratitles
version:      0.01
version_from: lib/WWW/Sucksub/Extratitles.pm
installdirs:  site
requires:
    Alias:                         >=2.3
    Carp:                          >= 1.0
    DB_File:                       >= 1.8
    HTTP::Cookies:                 >= 1.3
    Test::More:                    >=0.5
    WWW::Mechanize:                >= 1.2

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
